### ISSUE TITLE
Cant install.

### ISSUE THREAD

**Issue by gerenda110** [kus/csgo-modded-server#13]
Hello!
I ant to install, and after when finnish the uplod, i'll try to start, i cant start, i think the ptah, and other sm extensions wont works correktly or idk.  thats issue have on clean fresh SM  and meta mod. and i dont know why.. i'll delete the exts will start

<<<./srcds_run: 32: ./srcds_run: pushd: not found
./srcds_run: 35: ./srcds_run: popd: not found
LD_LIBRARY_PATH=/home/users/andrea0619/ftp/game/csgo_27160/bin:/home/users/andrea0619/ftp/game/csgo_27160:/home/users/andrea0619/ftp/game/csgo_27160/bin:
#
#Console initialized.
Setting breakpad minidump AppID = 740
#Using breakpad minidump system 740/13822.1443.DC
Using breakpad crash handler
Forcing breakpad minidump interfaces to load
dlopen failed trying to load:
/home/users/andrea0619/ftp/game/csgo_27160/.steam/sdk32/steamclient.so
with error:
/home/users/andrea0619/ftp/game/csgo_27160/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
/tmp/dumps is not owned by us - delete and recreate
Unable to delete /tmp/dumps. Continuing anyway.
#Loading VPK file hashes for pure server operation.
#Loading VPK file hashes for pure server operation.
#Loading VPK file hashes for pure server operation.
#Loading VPK file hashes for pure server operation.
#Loading VPK file hashes for pure server operation.
#Filesystem successfully switched to safe whitelist mode
#Game.dll loaded for "Counter-Strike: Global Offensive"
#CGameEventManager::AddListener: event 'server_pre_shutdown' unknown.
#CGameEventManager::AddListener: event 'game_newmap' unknown.
#CGameEventManager::AddListener: event 'finale_start' unknown.
#CGameEventManager::AddListener: event 'round_start' unknown.
#CGameEventManager::AddListener: event 'round_end' unknown.
#CGameEventManager::AddListener: event 'difficulty_changed' unknown.
#CGameEventManager::AddListener: event 'player_death' unknown.
#CGameEventManager::AddListener: event 'hltv_replay' unknown.
#CGameEventManager::AddListener: event 'player_connect' unknown.
#CGameEventManager::AddListener: event 'player_disconnect' unknown.
#GameTypes: missing mapgroupsSP entry for game type/mode (custom/custom).
#GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/cooperative).
#GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/coopmission).
Failed to load gamerulescvars.txt, game rules cvars might not be reported to management tools.
Server is hibernating
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
dlopen failed trying to load:
/home/users/andrea0619/ftp/game/csgo_27160/.steam/sdk32/steamclient.so
with error:
/home/users/andrea0619/ftp/game/csgo_27160/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Sys_LoadModule failed to load: /home/users/andrea0619/ftp/game/csgo_27160/.steam/sdk32/steamclient.so
No web api auth key specified - workshop downloads will be disabled.
 failed to dlopen /home/users/andrea0619/ftp/game/csgo_27160/csgo/addons/metamod/bin/linux64/server.so error=/home/users/andrea0619/ftp/game/csgo_27160/csgo/addons/metamod/bin/linux64/server.so: wrong ELF class: ELFCLASS64
Unable to load plugin "addons/metamod/bin/linux64/server"
PreMinidumpCallback: updating dump comment
crash_20220321153319_1.dmp[25003]: Uploading dump (out-of-process)

**Comment by gerenda110** [comment]
update:
i'll try every extensions  install, the server wont start....

**Comment by kus** [comment]
Is this running on a shared hosting provider?

`Unable to load plugin "addons/metamod/bin/linux64/server"` looks like the files aren't getting copied across correctly.

If you follow the [instructions here](https://github.com/kus/csgo-modded-server#running-on-linux) it should work if you have root access on a linux box. Shared hosting I'm not sure, I haven't tried it you would probably have to customise the script.

I run mine on Google cloud [like this](https://github.com/kus/csgo-modded-server#running-on-google-cloud) every Friday with these exact scripts and all works as expected, but I run it as root and have full access to the linux box.

**Comment by kus** [comment]
Hi @gerenda110,

I just updated the project to support Ubuntu 20.04.

Do you want to try again?

If it doesn't work can. you please give me full server console output

**Comment by biggydbs** [comment]
facing 
```
[S_API FAIL] SteamAPI_Init() failed; create pipe failed. failed to dlopen /home/steam/csgo/csgo/addons/metamod/bin/linux64/server.so error=/home/steam/csgo/csgo/addons/metamod/bin/linux64/server.so: wrong ELF class: ELFCLASS64
Unable to load plugin "addons/metamod/bin/linux64/server"
```

on ubuntu 20.04 @kus
