### ISSUE TITLE
I'm not understanding anything

### ISSUE THREAD

**Issue by nitrodenko** [kus/csgo-modded-server#14]
hi, i'm trying to open a server, but i have some problems when i try to start win.bat that is: I get "copying mod files" but i don't know where to find it

```
 If you want to quit, close the SRCDS window and type Y followed by Enter.
(14:05:38,98) Using SteamCMD to check for updates.
![unknown_2022 03 23-14 16_1](https://user-images.githubusercontent.com/49558980/159707489-40f9e290-5b77-46e4-8679-9ce4884a88aa.png)

(14:05:43,91) Copying mod files.
```

**Comment by kus** [comment]
Did you follow [these steps](https://github.com/kus/csgo-modded-server#running-on-windows)?

If you follow those steps exactly it should just work.

`(14:05:43,91) Copying mod files.` is the script copying the files from this repo over the CS default installation. You don't have to do anything.

I did a test on my Windows 10 machine following those exact steps and it works as expected.

This is what my command prompt shows

```
(17:02:54.99) Using SteamCMD to check for updates.
(17:31:00.20) Copying mod files.
(17:31:01.41) SRCDS started.
```

Make sure you accept the Windows firewall.

If it crashes, please show me crash error message, and try reopening first.

**Comment by kus** [comment]
`map load failed: am_skybound not found or invalid` It looks like the map doesn't exist.

Are you sure you have `am_skybound.bsp` in your `csgo/maps` folder?

Does ithe server work on a normal map like de_dust2?

**Comment by nitrodenko** [comment]
ok i made one part work, i miss the last one, every time i try to change game mode admin crashes the server

**Comment by kus** [comment]
Closed due to inactivity.

If it is still an issue, ensure you have updated your server to the latest CS:GO and using the latest version of this mod and reopen.
