### ISSUE TITLE
Crashing on load

### ISSUE THREAD

**Issue by Brramble** [kus/csgo-modded-server#15]
Hi, everytime I load a config through the !admin menu, the plugin loads but then 5 seconds later the server crashes. With -debug this is all I see in the console:

```
retake_settings.cfg executed 
retakes_game.cfg executed 
PutClientInServer: no info_player_start on level
Wrote minidump to: /home/steam/csgo/csgo/addons/sourcemod/data/dumps/bf84f62e-80b3-4a88-374892b8-ea6df594.dmp
Segmentation fault
cat: hlds.31056.pid: No such file or directory
email debug.log to linux@valvesoftware.com
Thu Apr 21 19:55:18 UTC 2022: Server restart in 10 seconds
WARNING: Could not locate steam dir:, ignoring.
```

Any ideas?

**Comment by kus** [comment]
Hi,

Could you give me the full server console output from server start to when you load a mod and it crashes?

Could you provide more information on your environment? OS/host etc

What script are you using to start the server?

**Comment by kus** [comment]
Closed due to inactivity.

If it is still an issue, ensure you have updated your server to the latest CS:GO and using the latest version of this mod and reopen.
