### ISSUE TITLE
Playing CSGO on the same PC that's running the server

### ISSUE THREAD

**Issue by apyr-behnam** [kus/csgo-modded-server#17]
Hey there!

Thanks for your wonderful server mod.

 I was just wondering, is it possible to play CS:GO on the same PC that's actually running the server?

Many thanks!

**Comment by apyr-behnam** [comment]
Oh, needless to say, this is for a LAN only situation.

**Comment by kus** [comment]
Yes you can run it locally and also play on the same PC.

I'm assuming you are on Windows, if so just follow the [Windows setup](https://github.com/kus/csgo-modded-server#running-on-windows).

It should run in a command prompt you need to leave open and then you should be able to join via the game.

**Comment by apyr-behnam** [comment]
Thanks for your response!

I am on Linux actually. Problem is when I run `./install.sh` to get the server running, Steam thinks that I'm already in game and won't let me go in game.

I have tried to run the game first and then run `./install.sh`, however in doing so I couldn't join my own server (I tried connecting to my own IP).

Am I doing something really wrong?

**Comment by kus** [comment]
Not sure about running it locally on LAN on Linux.

Did you follow the [LAN instructions](https://github.com/kus/csgo-modded-server#creating-a-lan-server)?

Do you have to open up ports in the firewall table at all?

I would say have the game open then run the server. Potentially an issue with it binding to the port.

**Comment by apyr-behnam** [comment]
Ok I managed to get it to work by running CSGO first and then executing `./install.sh`. However the trick was I had to connect to my own IP on port 27016, instead of the default 27015, i.e. I had to type `connect <ip_address>:27016`

Thanks again!
