### ISSUE TITLE
When I change game mode, Nothing happened...

### ISSUE THREAD

**Issue by kujourin** [kus/csgo-modded-server#18]
I change mode in admin menu, but nothing happened.
And then I change map... Map changed but game mode not change...
And then I change mod to PropHunt, nothing happened and players can't move...

**Comment by kus** [comment]
I'm going to need more information, are you running on Windows or Linux?

Local or hosted?

Which mods did you load in what order?

Try start the server and load Gungame first, let me know if that works.

Changing between mods can break the server, at the very end there is a "restart" CFG which crashes the server and restarts it automatically, which I recommend when changing between mods. Seems the mods never fully unload.

**Comment by kujourin** [comment]
I running it on my Windows Server.
First, I unzip csgo-modded-server-master.zip.
then unzip steamcmd.zip.
then modify the configuration file, like win.ini, secrets.cfg.
then run win.bat. It will download some files for a long time.
then it works.
I use the default settings to connect to the server.
everything is well.
!THEN I use sm_admin in console to change mods.
then I choose mods "PropHunt" in menu.
then change map. Nothing happened and players can't move.
then I restart server in admin menu.
server crash.
I must login it and run it again.

**Comment by kujourin** [comment]
Thanks, I have solved the problem.
