### ISSUE TITLE
Knives stopped working

### ISSUE THREAD

**Issue by Domantas-S** [kus/csgo-modded-server#21]
I believe a csgo update a couple weeks ago has broken the Weapons & Knives plugin. There is no output in the console when a user picks different knives with the !knife menu.

However, !ws and !glove work as expected.

I've updated sourcemod and metamod myself but they haven't fixed it.
I also tried updating the weapons & knives plugin but that didn't work.
What worked was updating PTaH but that seemed to break a lot of other things...
(source: https://forums.alliedmods.net/showthread.php?t=298770&page=183)

If you could fix this, I would appreciate it.

**Comment by kus** [comment]
Hi @Domantas-S,

Thanks for reporting this! I've updated PTaH and the Knives translations manually (the creator hasn't made a new release) and all seems to work again on my server.

Please let me know if this has fixed it for you, and close the issue if so.

**Comment by Domantas-S** [comment]
That's fixed it!
Thanks for getting on it so quickly 👍
