### ISSUE TITLE
Can u help me? 

### ISSUE THREAD

**Issue by ciropavic** [kus/csgo-modded-server#5]
How to turn on gungame??

Yust so ay not to forget!
My Linux ubuntu 18.04.4 could not install ./install.sh
I had to modify install.sh
Line 6.
PUBLIC_IP = $ (dig short myip.opendns.com @ resolutionver1.opendns.com)
in
PUBLIC_IP = $ (curl ifconfig.co)
And the installation succeeded

**Comment by kus** [comment]
Hi

You need to either run `exec gg.cfg` from the server console or RCON (see available mods here (remove `cfg/` when executing command) https://github.com/kus/csgo-modded-server/blob/master/csgo/addons/sourcemod/configs/adminmenu_cfgs.txt)

Or open the admin menu (once you have added yourself as an admin https://github.com/kus/csgo-modded-server#acessing-admin-menu) and choose Scripts > and choose a mod. The server will change map after the mod loads which it must do to refresh everything.

If you change between lots of mods sometimes things can get left over from a previous mod - so it's recommended to run the Restart script which will restart the server and it should be back up in 20 seconds.

RE: Ubuntu 18.04.4 I'm still running on Ubuntu 16 so haven't tested on 18. Not sure why `dig +short myip.opendns.com @resolver1.opendns.com` wouldn't work though :\
