### ISSUE TITLE
Bots are standing still in deathmatch mode

### ISSUE THREAD

**Issue by Toutzn** [kus/csgo-modded-server#6]
Hi,

first I would say big big thanks for your big work on that modded server! This is fantastic!
could you explain in you're readme what is needed to enable bots working in deathmatch mode? 

Thanks a lot

**Comment by sfhsjr** [comment]
In the ./csgo/cfg/gamemode_deathmatch.cfg file change the line:

`mp_bot_ai_bt                                                                            "scripts/ai/deathmatch/bt_default.kv3"`

to:

`mp_bot_ai_bt                                                                            "scripts/ai/deathmatch/bt_config.kv3"`

There is an issue with the custom bot ai settings.

Then in the ./csgo/cfg/deathmatch_settings.cfg file delete the line:
 
`bot_kick`

Then, add in these few bot setting lines. This will make the server have a minimum of 5 players/bots when a person joins a team:
```

bot_chatter                                                     "off"
bot_join_after_player                           1
bot_quota                                                       5
bot_quota_mode                                          "fill"
bot_difficulty                                  3
```
