### ISSUE TITLE
[request] Voting system

### ISSUE THREAD

**Issue by parsman** [kus/csgo-modded-server#9]
Hi, thank you.
If you add a graphical voting system in addition to a map voting system, it would be great having a real multimode server which changes modes automatically.

**Comment by kus** [comment]
Sorry I'm not a plugin developer. I just download and configure existing plugins.

By all means if you find an existing plugin that does this, I can add it to this server.

You could have a look around here https://forums.alliedmods.net/forumdisplay.php?f=108 or even request it to be built there.
